version: "3.7"
services:
  realmysql-db:
    image: mysql:8.0.21
    container_name: realmysql-employee
    ports:
      - "23306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root-pass
      - MYSQL_USER=realmysql
      - MYSQL_PASSWORD=realmysql
      - TZ=UTC
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
      - --lower_case_table_names=1
    volumes:
      - ./.mysql:/var/lib/mysql